### ISSUE TITLE
Crash on equipping certain items in the left hand

### ISSUE THREAD

**Issue by Tomsod** [Malekitsu/MM6-MAW-TCC-Version#1]
TCC adds two specitems: Right Hand Sword of Grish'nak (id 545) and Loki’s Right Hand Blade (id 555).  Like the names suggests, they must only be equipped in the right hand, because the game crashes when the left hand is used!  Now, I suspect this is a limitation of the MM6 engine (too high id perhaps?), and TCC devs just rationalized it ingame, but it still would be more humane to properly forbid left-hand use of those items instead of the crash.

**Comment by Eksekk** [comment]
Confirming this is not MAW-specific, it happened to me persistently with vanilla TCC install loooong time ago. Do you think simple "error sound" when equipping in left hand would be enough?

**Comment by Tomsod** [comment]
Either that, or just treat them as right-hand-only weapons like maces, i.e. equip in the right hand no matter where on the paperdoll they're placed.
